version: '3.8'

services:
  app:
    build: .
    ports:
      - "9090:9090"
    command: ["./main"]

  test:
    image: golang:1.18
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - app
    command: ["go", "test", "-v", "./..."]
