version: '3.8'

services:
  app:
    build: .
    ports:
      - "9090:9090"
    command: ["./main"]

  test:
    image: golang:1.18
    working_dir: /app
    volumes:
      - .:/app
      - report-data:/report-data
    depends_on:
      - app
    command: >
      sh -c "go test -v ./... | tee test-results.out &&
             go-test-report -input test-results.out -output /report-data/test-report.html"

volumes:
  report-data:
